name: Deploy porteFolio-V2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH test
        uses: appleboy/ssh-action@master
        with:
          script: |
            sudo npm install
            sudo npm run build
