name: Deploy porteFolio-V2

on:
  push:
    branches:
      - test-git-actions 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: npm ci
      
      - name: build
        run: npm run build
      

      
