name: Deploy porteFolio-V2

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: local
        with:
          script: |
            sudo npm install
            sudo npm run build
